#!/bin/sh
# ## ##################################################################
# /etc/init.d/S10i2cperms
#
# Changes group and permissions for all I²C devices to root:i2c / ug+rw
# Author: Mauricio Matamoros
#
# ## ##################################################################

case "${1}" in
    start)
        # Loops over all i2c devices, if any
        for iic in /dev/i2c*; do
            chown root:i2c "${iic}"
            chmod ug+rw "${iic}"
        done
        unset iic
        ;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac
